### ISSUE TITLE
Bådplads

### ISSUE THREAD

**Issue by CasperJ** [fisketorvetsmotorbaadklub/fisketorvetsmotorbaadklub.github.io#1]
Hej @iamfrank, @NicolaiNyberg og @FMKlub 

Jeg er interesseret i at komme i kontakt med bådklubben. Jeg snakkede med en af medlemmerne på havnen som opfordrede mig til at skrive til `fmk-kbh[at]hotmail.dk`. Jeg har intet hørt så jeg tænkte, at en af Jer måske kunne hjælpe mig med kontakten.

Tak og god søndag
Mvh.
Casper

**Comment by iamfrank** [comment]
Hej Casper

Jeg har ikke været medlem i bådklubben i årevis, så jeg kan desværre ikke hjælpe. 
Men forsøg deres Facebook page: https://www.facebook.com/pages/Fisketorvets-Motorb%C3%A5dsklub-FMK/157238980994747

Mvh,
Frank
